#+title: My NixOS configuration
#+PROPERTY: header-args:bash :noeval

* Quick Start

Apply configuration changes:

#+begin_src bash
just switch
#+end_src

* Update

Update the flake inputs and rebuild:

#+begin_src bash
just update
#+end_src

Or just update flake.lock without rebuilding:

#+begin_src bash
just flake
#+end_src

* Bootstrap a New NixOS System

Clone the repo:

#+begin_src bash
git clone git@github.com:stfl/dotfiles.git ~/.config/dotfiles
#+end_src

** Setup Emacs

https://github.com/stfl/doom.d#installation

* System Configuration
** Access user journal

Grant user access to system journal:

#+begin_src bash :dir /sudo::
usermod -a -G systemd-journal $USER
#+end_src

** Set default boot target to multi-user

For headless systems:

#+begin_src bash :dir /sudo::
systemctl set-default multi-user.target
#+end_src

** Hardware: ZSA Keyboards

ZSA keyboard support (ErgoDox EZ, Moonlander, Voyager) is configured in ~modules/hardware/zsa.nix~.

The udev rules and plugdev group setup are handled automatically by NixOS.

** Docker

Docker is configured via ~modules/docker.nix~. The module handles:
- Installing docker and docker-compose
- Adding the user to the docker group
- Enabling the docker service

** Bashrc for root

Symlink root's .bashrc to the versioned config:

#+begin_src bash :dir /sudo:: :results value
ln /home/slendl/.config/dotfiles/config/bash/.bashrc.root /root/.bashrc -sf
#+end_src

* Development Tools
** password-store

Trust your password-store GPG key:

#+begin_src bash :noeval
gpg --edit-key <password-store-key>
> trust
> 5 # trust ultimately
#+end_src

** org-protocol in Brave Browser

[[https://www.reddit.com/r/emacs/comments/icjaie/orgprotocol_users_is_there_a_way_to_disable/][Reddit about policy]]
[[https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy][Brave Doku]]

Install the org-protocol policy system-wide:

#+begin_src json :tangle /sudo::/etc/brave/policies/managed/org-protocol.json :mkdirp t
{
  "AutoLaunchProtocolsFromOrigins": [
    {
      "allowed_origins": [ "*" ],
      "protocol": "org-protocol2"
    }
  ]
}
#+end_src

[[https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/browsers/brave/default.nix#L187C36-L187C51][Brave nix source]]

* NixOS Operations
** Building and switching

Local rebuild:

#+begin_src bash :noeval
sudo nixos-rebuild switch --flake ".#"
#+end_src

** Remote deployment

Deploy to a remote host:

#+begin_src bash :noeval
nixos-rebuild \
    --target-host stefan@192.168.31.217 \
    --use-remote-sudo \
    switch \
    --flake ".#hostname"
#+end_src

* NixOS Installation

The easiest solution is to do a remote setup - have the nixos config on an
existing machine and connect to the new system via ssh.

On the installation target, change the password so that ssh will work:

#+begin_src bash :noeval
passwd
#+end_src

** Partitioning

Partitioning with an ESP and a single large partition with ext4:

#+begin_export bash :noeval
parted /dev/sda -- mklabel gpt
parted /dev/sda -- mkpart ESP fat32 1MiB 512MiB
parted /dev/sda -- mkpart primary linux-swap 512MiB 8.5GiB
parted /dev/sda -- mkpart primary 8.5GiB 100%
parted /dev/sda -- set 1 boot on
mkfs.fat -F32 -n BOOT /dev/sda1
mkswap -L swap /dev/sda2
mkfs.ext4 -L nixos /dev/sda3
#+end_export

** Setup

Mount partitions:

#+begin_src bash :noeval
mount /dev/sda3 /mnt
mkdir -p /mnt/boot
mount /dev/sda1 /mnt/boot
swapon /dev/sda2
#+end_src

Generate the hardware-configuration.nix:

#+begin_src bash :noeval
nixos-generate-config --root /mnt --dir .
#+end_src

Copy the hardware-configuration to the git repo:

#+begin_src bash
HOST=kondor
mkdir -p hosts/$HOST
scp nixos@192.168.11.11:hardware-configuration.nix hosts/$HOST
cp hosts/nixos-vm/{default,home}.nix hosts/$HOST
#+end_src

Then customize =hardware-configuration.nix, default.nix and home.nix=

** Installation

Get the config to the target (rsync won't work if not available on target):

#+begin_src bash
rsync -ravh ./ nixos@192.168.11.11:dotfiles/
#+end_src

On the target, run nixos-install:

#+begin_src bash :noeval
HOST=kondor
nixos-install --root /mnt --flake .#$HOST
#+end_src

** Repair NixOS Installation via Live ISO
:PROPERTIES:
:ID:       ef647d22-567a-4a19-8fbd-e0cf897cd69e
:END:

To repair a NixOS installation when booted to a live ISO:

Mount the partitions to ~/mnt~ and enter the special nixos chroot:

#+begin_src bash :noeval
nixos-enter
#+end_src

#+begin_src bash :noeval
cd /path/to/dotfiles
nixos-rebuild switch --flake .#hostname
#+end_src

* Secrets Management with agenix
** Add a new secret

Modify [[file:secrets/secrets.nix]] and add the new secret file.

** Create and edit a secret

#+begin_src bash
cd secrets
agenix -e <name-of-secret>.age
#+end_src

Emacs will open and you can insert the content to modify or create a new file.
=Save the file= and close with =SPC b k= to terminate the buffer and return to the shell.

** Add a new host

- You need to first setup NixOS without agenix
- Put the auto-generated ssh host public key ~/etc/ssh/ssh_host_ed25519_key.pub~ into secrets.nix
- Rekey with another private key that allows decrypting all relevant keys:

#+begin_src bash
agenix --rekey -i ~/.ssh/id_ed25519_stfl
#+end_src

* Create a Custom ISO

Edit [[file:modules/iso.nix]], then build:

#+begin_src bash
nix build .#iso
#+end_src

Write to USB:

#+begin_src bash
sudo dd if=results/iso/*.iso of=/dev/sda bs=4M status=progress && sync
#+end_src

* Application Setup
** Citrix Workspace

Download the corresponding version from https://www.citrix.com/downloads/workspace-app/

Add the file to the nix store:

#+begin_src bash
nix-prefetch-url file://${PWD}/packages/citrix/linuxx64-24.8.0.98.tar.gz
#+end_src

Afterwards citrix_workspace can be installed.

** Stremio + Torrentio
:PROPERTIES:
:ID:       55ae4a58-0b99-4595-98c7-0c3a047018ea
:END:

https://torrentio.strem.fun/providers=yts,eztv,rarbg,1337x,thepiratebay,kickasstorrents,torrentgalaxy,magnetdl,horriblesubs,nyaasi,tokyotosho,anidex%7Clanguage=german%7Cqualityfilter=threed,480p,scr,cam,unknown%7Climit=10/configure

** Steam

https://wiki.nixos.org/wiki/Steam

Steam is configured via ~modules/steam.nix~.

Starting steam within gamescope:

#+begin_src bash
export AMD_VULKAN_ICD="RADV"
gamescope --adaptive-sync --hdr-enabled --rt --steam -- \
    steam -pipewire-dmabuf -tenfoot
#+end_src

* Display Configuration
** Kanshi

Get current output information:

#+begin_src sh :results silent verbatim
swaymsg -t get_outputs
#+end_src

Display profiles are configured per-host in the home-manager configuration.

* FlakeHub

Login to FlakeHub for faster downloads and cache:

#+begin_src bash
determinate-nixd login
#+end_src

* Hyprland
** Monitors

#+begin_src bash
hyprctl monitors all
#+end_src

* Configure rclone

rclone has many different endpoints it can set up.

I believe, the easiest to set up an endpoint is to run the ~rclone config~ wizard
and copy the resulting confing including secrets from
~~/.config/rclone/rclone.conf~ into the nixos module and agenix secrets
respectivly

** Update Google Drive token

https://rclone.org/drive/

- in [[modules/home/rclone-shares.nix]] configure ~config.client_id~ and ~secrets.client_secret~. (without ~secrets.token~)
- rebuild the system
- /possibly/ remove the token value from ~~/.config/rclone/rclone.conf~
- run ~rclone config~ and reconfigure the drive endpoint.
- after authenticating the client, copy the **token** value from ~~/.config/rclone/rclone.conf~
  into the ~secrets/rclone-drive-token.age~ via [[*Secrets Management with agenix]].
  This token value contians the refresh_token that allows the client to stay online
- rebuild the system with ~secrets.token~ set to the agenix secret in [[modules/home/rclone-shares.nix]]
