#+PROPERTY: header-args :results silent
#+title: My nix home-manager config

#+begin_src bash
nix run . -- build -b backup --flake .
#+end_src

#+begin_src bash
nix run . -- switch -b backup --flake .
#+end_src

* Setup nix on Debian 12

add user to sudoers (because it's much more convinient)

#+begin_src bash :noeval
/sbin/usermod -a -G sudo $USER
#+end_src

install package ~nix-setup-systemd~

#+begin_src bash
apt-get -y install nix nix-setup-systemd
#+end_src

Add user to ~nix-users~ group

#+begin_src bash :noeval
/sbin/usermod -a -G nix-users $USER
#+end_src

reboot // logout>login

update global nix config config
[[file:/sudo::/etc/nix/nix.conf]]

#+begin_src conf :tangle no
max-jobs = auto

experimental-features = nix-command flakes
#+end_src

* Bootstrap the config

Install git (which is not present on PVE base install)

#+begin_src bash
apt-get install -y git
#+end_src

Clone the repo

#+begin_src bash
git clone git@github.com:stfl/dotfiles.git ~/.config/dotfiles
#+end_src

#+begin_src bash :noeval
nix run . -- switch -b backup --flake .
#+end_src

** Setup Emacs

https://github.com/stfl/doom.d#installation

** swaylock
[2023-09-07 Thu] - swaylock from nix does not work with home-manager on Debian with LDAP...

install swaylock from Debian repo

#+begin_src bash
apt install swaylock
#+end_src

~UPDATE~ not using LDAP anymore..
TODO: swaylock requires some pam config..

#+begin_quote
cat /etc/pam.d/swaylock
#
# PAM configuration file for the swaylock screen locker. By default, it includes
# the 'login' configuration file (see /etc/pam.d/login)
#

auth include login
#+end_quote
** TODO set nix installed zsh as default shell

=NOTE= *this will not work on the Workstation at Proxmox with LDAP login because
the login shell is configured via LDAP*

when trying to set a nix installed shell as default it will cause an error as follows:

#+begin_quote bash
chsh -s /home/stefan/.nix-profile/bin/zsh
Password:
chsh: /home/stefan/.nix-profile/bin/zsh is an invalid shell
#+end_quote

manually ad ~/home/stefan/.nix-profile/bin/zsh~ to [[file:/etc/passwd]]

Alternatively, add the following to [[file:/etc/shells]] to mark nix installed shells as valid shells.

#+begin_src txt
/home/stefan/.nix-profile/bin/zsh
/home/stefan/.nix-profile/bin/bash
/home/stefan/.nix-profile/bin/fish
#+end_src

then run this to enabel this shell

#+begin_src bash
chsh -s /home/stefan/.nix-profile/bin/zsh
#+end_src

On the Proxmox workstation setting ~~/.nix-profile/bin/zsh~ as the login shell does not work because it is set set via LDAP.
As a workaround I install zsh via apt, set ~/bin/zsh~ as LDAP Login shell and still set ~programs.zsh.enable = true~ in nix.

/Let's hope the versions and nix config will not diverge too much..../
** Access user journal

Per default, I cannot access the user's own journal ~journalctl --user~. I am fine with granting access to the system's journal.

#+begin_src bash :dir /sudo::
/sbin/usermod -a -G systemd-journal slendl
#+end_src
** Set default boot target to multi-user

#+begin_src bash :dir /sudo::
systemctl set-default multi-user.target
#+end_src

* Install in Debian System
:PROPERTIES:
:ID:       ef6f0b51-2c53-4029-839b-8e46b6c96ada
:END:

some packages need to be installed in the Debian System itself for various reasons.
The following list is very likely outdated!!

for building some things in emacs (vterm, sqlite) I need built tools. I don't
want to polute my dev environment - which requires Debian build tooling - I need
to install these from the system.

- build-essential
- cmake
- libtool
- libtool-bin
- libnotify-bin

starting sway from login shell

#+begin_src bash
echo "---- RESTART ----" >>| ~/.cache/sway.log && \
    nixGLIntel sway &>> ~/.cache/sway.log
#+end_src

Even though I patched the ~wayland.windowManager.sway.package~ with nixGL it does
not start up properly, so I need to start it with the nixGL wrapper

swaylock does not work (still true?) from nix.. so use swaylock from the system

- swaylock

* Setup Syncthing
* Configure logind on Debian 12

I am using i3wm, installed through nix home-manager. System-wide configuration
like logind to configure PowerKey and so on cannot be managed through
home-manager and need to be configured separately.

=NOTE= Tangle a single src block with ~C-u~ prefix command or ~SPC u~ in doomemacs.
- ~SPC u C-c C-v t~

** with hibernate

If hibernate is working use

~/etc/systemd/logind.conf.d/90_config.conf~
#+begin_src conf :mkdirp yes :tangle /sudo::/etc/systemd/logind.conf.d/90_config.conf
[Login]
HandlePowerKey=suspend-then-hibernate
IdleAction=suspend-then-hibernate
IdleActionSec=20m
#+end_src

~/etc/systemd/sleep.conf.d/90_config.conf~
#+begin_src conf :mkdirp yes :tangle /sudo::/etc/systemd/sleep.conf.d/90_config.conf
[Sleep]
HibernateDelaySec=1h
#+end_src

** without hibernate

~/etc/systemd/logind.conf.d/90_config.conf~
#+begin_src conf :mkdirp yes :tangle /sudo::/etc/systemd/logind.conf.d/90_config.conf
[Login]
HandlePowerKey=suspend
IdleAction=suspend
IdleActionSec=20m
#+end_src

** reload systemd config

#+begin_src bash :dir /sudo:: :results value
systemctl daemon-reload
#+end_src
* Docker

Installing Docker via home-manager dow not make any sense, does it?
Install it directly via apt

#+begin_src bash :dir /sudo::
apt-get install docker docker-compose -y
#+end_src

Add unprivileged user ~stefan~ to the ~docker~ group to enable interacting with the docker daemon without sudo.

#+begin_src bash :dir /sudo::
usermod -a -G docker $USER
#+end_src

reboot
* E-Mail setup

after first installation, sync the mailbox

#+begin_src bash
mbsync -a
#+end_src

and init notmuch

#+begin_src bash
notmuch new
#+end_src
