# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  nixos-hardware,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    nixos-hardware.nixosModules.lenovo-thinkpad-t490
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/ROOT";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # SWAP is already in the LUKS encrypted partition
  swapDevices = [ { device = "/dev/disk/by-label/SWAP"; } ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "nvme"
        "usb_storage"
        "sd_mod"
        "sdhci_pci"
      ];
      kernelModules = [
        "dm-snapshot"
        "cryptd"
      ];
      luks.devices."encrypted".device = "/dev/disk/by-label/LUKS";
    };

    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    # Disable Intel GPU mitigations
    kernelParams = [ "i915.mitigations=off" ];

    resumeDevice = "/dev/disk/by-label/SWAP";

    loader = {
      systemd-boot = {
        enable = true;
        configurationLimit = 20;
        # graceful = true;
        memtest86.enable = true;
      };
      efi.canTouchEfiVariables = false;
      timeout = 5;
    };
  };

  powerManagement.powertop.enable = true;

  nixpkgs.hostPlatform = "x86_64-linux";

  hardware = {
    enableAllFirmware = true;
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        libva-vdpau-driver
      ];
    };
  };
}
